spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.h2.console.enabled=false

jwt.secret=${JWT_SECRET}
truetrace.security.sync-token=${TRUETRACE_SECURITY_SYNC_TOKEN}
truetrace.security.allowed-origins=${TRUETRACE_ALLOWED_ORIGINS}
truetrace.demo.seed-enabled=false
